/*
 * MATLAB Compiler: 4.1 (R14SP1)
 * Date: Sat Dec 29 13:24:49 2012
 * Arguments: "-B" "macro_default" "-m" "-W" "main" "-T" "link:exe"
 * "project_ofdm_gui.m" "-a" "project_ofdm_gui.fig" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_project_ofdm_gui_public_data[] = {'3', '0', '8',
                                                            '1', '9', 'D',
                                                            '3', '0', '0',
                                                            'D', '0', '6',
                                                            '0', '9', '2',
                                                            'A', '8', '6',
                                                            '4', '8', '8',
                                                            '6', 'F', '7',
                                                            '0', 'D', '0',
                                                            '1', '0', '1',
                                                            '0', '1', '0',
                                                            '5', '0', '0',
                                                            '0', '3', '8',
                                                            '1', '8', 'B',
                                                            '0', '0', '3',
                                                            '0', '8', '1',
                                                            '8', '7', '0',
                                                            '2', '8', '1',
                                                            '8', '1', '0',
                                                            '0', 'C', '4',
                                                            '9', 'C', 'A',
                                                            'C', '3', '4',
                                                            'E', 'D', '1',
                                                            '3', 'A', '5',
                                                            '2', '0', '6',
                                                            '5', '8', 'F',
                                                            '6', 'F', '8',
                                                            'E', '0', '1',
                                                            '3', '8', 'C',
                                                            '4', '3', '1',
                                                            '5', 'B', '4',
                                                            '3', '1', '5',
                                                            '2', '7', '7',
                                                            'E', 'D', '3',
                                                            'F', '7', 'D',
                                                            'A', 'E', '5',
                                                            '3', '0', '9',
                                                            '9', 'D', 'B',
                                                            '0', '8', 'E',
                                                            'E', '5', '8',
                                                            '9', 'F', '8',
                                                            '0', '4', 'D',
                                                            '4', 'B', '9',
                                                            '8', '1', '3',
                                                            '2', '6', 'A',
                                                            '5', '2', 'C',
                                                            'C', 'E', '4',
                                                            '3', '8', '2',
                                                            'E', '9', 'F',
                                                            '2', 'B', '4',
                                                            'D', '0', '8',
                                                            '5', 'E', 'B',
                                                            '9', '5', '0',
                                                            'C', '7', 'A',
                                                            'B', '1', '2',
                                                            'E', 'D', 'E',
                                                            '2', 'D', '4',
                                                            '1', '2', '9',
                                                            '7', '8', '2',
                                                            '0', 'E', '6',
                                                            '3', '7', '7',
                                                            'A', '5', 'F',
                                                            'E', 'B', '5',
                                                            '6', '8', '9',
                                                            'D', '4', 'E',
                                                            '6', '0', '3',
                                                            '2', 'F', '6',
                                                            '0', 'C', '4',
                                                            '3', '0', '7',
                                                            '4', 'A', '0',
                                                            '4', 'C', '2',
                                                            '6', 'A', 'B',
                                                            '7', '2', 'F',
                                                            '5', '4', 'B',
                                                            '5', '1', 'B',
                                                            'B', '4', '6',
                                                            '0', '5', '7',
                                                            '8', '7', '8',
                                                            '5', 'B', '1',
                                                            '9', '9', '0',
                                                            '1', '4', '3',
                                                            '1', '4', 'A',
                                                            '6', '5', 'F',
                                                            '0', '9', '0',
                                                            'B', '6', '1',
                                                            'F', 'C', '2',
                                                            '0', '1', '6',
                                                            '9', '4', '5',
                                                            '3', 'B', '5',
                                                            '8', 'F', 'C',
                                                            '8', 'B', 'A',
                                                            '4', '3', 'E',
                                                            '6', '7', '7',
                                                            '6', 'E', 'B',
                                                            '7', 'E', 'C',
                                                            'D', '3', '1',
                                                            '7', '8', 'B',
                                                            '5', '6', 'A',
                                                            'B', '0', 'F',
                                                            'A', '0', '6',
                                                            'D', 'D', '6',
                                                            '4', '9', '6',
                                                            '7', 'C', 'B',
                                                            '1', '4', '9',
                                                            'E', '5', '0',
                                                            '2', '0', '1',
                                                            '1', '1', '\0'};

const char *__MCC_project_ofdm_gui_name_data = "project_ofdm_gui";

const char *__MCC_project_ofdm_gui_root_data = "";

const unsigned char __MCC_project_ofdm_gui_session_data[] = {'7', '4', '8',
                                                             '4', 'A', '9',
                                                             'A', '0', '4',
                                                             '7', 'D', 'B',
                                                             '1', '0', 'E',
                                                             '5', '8', 'A',
                                                             '1', '6', '8',
                                                             '2', '7', 'B',
                                                             '9', '3', 'E',
                                                             '4', '3', '8',
                                                             '0', 'D', 'F',
                                                             '7', '7', '0',
                                                             '2', '6', '1',
                                                             'B', 'D', 'B',
                                                             '7', '9', '0',
                                                             '2', 'E', '7',
                                                             'B', 'F', '5',
                                                             '7', '1', '2',
                                                             '6', '4', '5',
                                                             '8', '8', 'F',
                                                             '6', 'F', '1',
                                                             '3', 'E', 'D',
                                                             'A', 'F', '1',
                                                             'E', 'D', '8',
                                                             'A', '6', '5',
                                                             'D', '5', 'C',
                                                             'E', '3', '2',
                                                             '6', '4', '8',
                                                             '8', 'E', 'D',
                                                             'C', '5', 'A',
                                                             '7', 'B', '9',
                                                             'C', 'E', '3',
                                                             '2', 'B', '9',
                                                             '9', '4', 'D',
                                                             'E', 'D', '8',
                                                             'A', '6', '8',
                                                             '6', 'B', 'B',
                                                             '3', '3', '4',
                                                             'B', '8', 'F',
                                                             'B', '0', '2',
                                                             '5', 'E', '4',
                                                             'E', '7', '0',
                                                             '3', '6', '3',
                                                             'B', 'E', '8',
                                                             '2', '1', 'F',
                                                             'D', 'A', 'E',
                                                             '6', '0', '1',
                                                             '3', 'A', '8',
                                                             '2', '0', '3',
                                                             'D', '3', 'E',
                                                             '3', '3', '3',
                                                             'F', '9', '2',
                                                             '7', '5', 'B',
                                                             '9', 'A', '0',
                                                             '1', '9', 'C',
                                                             'F', '0', '3',
                                                             '0', '1', '5',
                                                             '5', 'A', '4',
                                                             '6', '2', '5',
                                                             '3', 'C', 'B',
                                                             '6', '4', '0',
                                                             'B', '9', 'A',
                                                             'C', 'D', 'A',
                                                             'C', '6', 'C',
                                                             '6', '4', '8',
                                                             '4', 'E', 'B',
                                                             'C', 'E', '4',
                                                             '9', '5', 'D',
                                                             'E', '7', '2',
                                                             'D', 'A', '1',
                                                             '4', '2', '5',
                                                             '9', '4', '2',
                                                             '8', '9', '7',
                                                             '2', '5', 'E',
                                                             'C', '6', '1',
                                                             'F', 'A', 'B',
                                                             '8', 'E', 'A',
                                                             '4', 'C', '1',
                                                             '3', 'E', '8',
                                                             '0', 'F', '5',
                                                             '7', 'F', '9',
                                                             '2', '7', 'A',
                                                             '3', '2', 'D',
                                                             'E', 'F', '8',
                                                             'E', 'B', 'D',
                                                             'B', '\0'};

const char *__MCC_project_ofdm_gui_matlabpath_data[] = {"project_ofdm_gui/",
                                                        "work/project_ofdm/Project ofdm_exe/",
                                                        "toolbox/compiler/deploy/",
                                                        "$TOOLBOXMATLABDIR/general/",
                                                        "$TOOLBOXMATLABDIR/ops/",
                                                        "$TOOLBOXMATLABDIR/lang/",
                                                        "$TOOLBOXMATLABDIR/elmat/",
                                                        "$TOOLBOXMATLABDIR/elfun/",
                                                        "$TOOLBOXMATLABDIR/specfun/",
                                                        "$TOOLBOXMATLABDIR/matfun/",
                                                        "$TOOLBOXMATLABDIR/datafun/",
                                                        "$TOOLBOXMATLABDIR/polyfun/",
                                                        "$TOOLBOXMATLABDIR/funfun/",
                                                        "$TOOLBOXMATLABDIR/sparfun/",
                                                        "$TOOLBOXMATLABDIR/scribe/",
                                                        "$TOOLBOXMATLABDIR/graph2d/",
                                                        "$TOOLBOXMATLABDIR/graph3d/",
                                                        "$TOOLBOXMATLABDIR/specgraph/",
                                                        "$TOOLBOXMATLABDIR/graphics/",
                                                        "$TOOLBOXMATLABDIR/uitools/",
                                                        "$TOOLBOXMATLABDIR/strfun/",
                                                        "$TOOLBOXMATLABDIR/imagesci/",
                                                        "$TOOLBOXMATLABDIR/iofun/",
                                                        "$TOOLBOXMATLABDIR/audiovideo/",
                                                        "$TOOLBOXMATLABDIR/timefun/",
                                                        "$TOOLBOXMATLABDIR/datatypes/",
                                                        "$TOOLBOXMATLABDIR/verctrl/",
                                                        "$TOOLBOXMATLABDIR/codetools/",
                                                        "$TOOLBOXMATLABDIR/helptools/",
                                                        "$TOOLBOXMATLABDIR/winfun/",
                                                        "$TOOLBOXMATLABDIR/demos/",
                                                        "toolbox/local/",
                                                        "toolbox/stateflow/stateflow/",
                                                        "toolbox/comm/comm/",
                                                        "toolbox/compiler/",
                                                        "toolbox/control/control/",
                                                        "toolbox/database/database/",
                                                        "toolbox/mbc/mbc/",
                                                        "toolbox/nnet/nnet/",
                                                        "toolbox/nnet/nnutils/",
                                                        "toolbox/robust/robust/",
                                                        "toolbox/symbolic/"};
const int __MCC_project_ofdm_gui_matlabpath_data_count = 42;

const char *__MCC_project_ofdm_gui_classpath_data[] = {"java/jar/toolbox/control.jar",
                                                       "java/jar/toolbox/database.jar"};
const int __MCC_project_ofdm_gui_classpath_data_count = 2;

const char *__MCC_project_ofdm_gui_mcr_application_options[] = { "" };
const int __MCC_project_ofdm_gui_mcr_application_option_count = 0;
const char *__MCC_project_ofdm_gui_mcr_runtime_options[] = { "" };
const int __MCC_project_ofdm_gui_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


